source:      .
destination: ./_site
plugins:     ./_plugins

pygments: true
future: true
permalink: articles/:year/:month/:day/:title

paginate: 3
paginate_file: articles.html

tag_page_layout: tag
tag_page_dir: tags

markdown: redcarpet2

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]
