blog:
  title: "Matt Sears"
  subtitle: ""
  name:  "@mattsears"
  author: "Matt Sears"
  email:  "matt@mattsears.com"
  directory: "app/articles"

ga_code: "{REPLACE WITH YOUR GOOGLE ANALYTICS CODE OR LEAVE EMPTY}"

public:
  directory: "public"

theme:
  name: "views"
  directory: "app"

pages:
  directory: "pages"

git:
  url: "git@github.com:mattsears/mattsears.git"
  name: "origin"
  branch: "master"

remote_repository: "git://github.com/mattsears/mattsears.com.git"

# If you want to add synchronizing via Github post-receive hooks, insert some secure password here
# Then set a "Post-Receive URL" in Github administration to http://{YOUR SERVER}/sync?token={WHAT YOU SET BELOW}
github_token: ~

# See http://soakedandsoaped.com/articles/2006/10/01/how-to-protect-a-rails-application-against-spam-with-akismet
akismet:
  key: "{REPLACE WITH YOUR AKISMET KEY}"
  url: "{REPLACE WITH YOUR AKISMET URL}"

# http://antispam.typepad.com/info/developers.html
typekey_antispam:
  key: "{REPLACE WITH YOUR TYPEKEY ANTISPAM URL}"
  url: "{REPLACE WITH YOUR BLOG URL}"
